cookie:
  expiry_days: 30
  key: abcd
  name: dostai
credentials:
  usernames:
    anubhavyadav:
      age: 20
      chatbot_nickname: Abhi
      designation: Healthcare Worker
      email: anubhavyadav@gmail.com
      gender: Male
      name: Anubhav Yadav
      password: $2b$12$DQbhBISZUO1UZGmQM8.BcePwgX1VQZBHq6KK88GHDthC4vdB.n8U.
      preferred_lang: German
      prob_facing: Both
      prob_reason: Professional
      status: Single
      vegan_or_nonvegan: Non-Vegan
      working_hours: 10
      working_place: Hospital
    priyanshu123:
      age: 24
      chatbot_nickname: Keshu
      designation: Doctor
      email: priyanshu@gmail.com
      gender: Male
      logged_in: false
      name: Priyanshu Joshi
      password: $2b$12$1rYWtQqsf8G7qtwAOArFvuepWgfHywtR45JlIgQr/g.P2YAAuBFX.
      preferred_lang: English
      prob_facing: Mental Health
      prob_reason: Professional
      status: Single
      working_hours: 12
      working_place: Hospital
