cookie:
  expiry_days: 30
  key: abcd
  name: dostai
credentials:
  usernames:
    priyanshu123:
      age: 24
      designation: Doctor
      email: priyanshu@gmail.com
      gender: Male
      name: Priyanshu Joshi
      password: $2b$12$1rYWtQqsf8G7qtwAOArFvuepWgfHywtR45JlIgQr/g.P2YAAuBFX.
      preferred_lang: English
      prob_facing: Mental Health
      prob_reason: Professional
      status: Single
      working_hours: 12
      working_place: Hospital
