cookie:
  expiry_days: 30
  key: abcd
  name: dostai
credentials:
  usernames:
    priyanshu2025:
      age: 23
      chatbot_nickname: Dost
      designation: Doctor
      email: priyanshu@gmail.com
      gender: Male
      name: Priyanshu Joshi
      password: $2b$12$pnm3EWTwwxWlhd7pZV66gug.4xbvL8D4FSyExfDq8.0PREac6WUFW
      preferred_lang: English
      prob_facing: Mental Health
      prob_reason: Professional
      status: Single
      vegan_or_nonvegan: Vegan
      working_hours: 14
      working_place: Hospital
